version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root  
       MYSQL_DATABASE: glazik
       MYSQL_USER: root
       MYSQL_PASSWORD: root
