version: '3.1'

services:
  nginx:
    build: ./nginx
    ports:
    - 80:80
    volumes:
        - ./nginx/glazik-site:/code
    links:
        - php
  php:
    image: php:7.3-fpm
    volumes:
        - ./nginx/glazik-site:/code
  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080
  db:
    image: mysql:5.6
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root  
       MYSQL_DATABASE: glazik
       MYSQL_USER: root
       MYSQL_PASSWORD: root
